version: '3'
services:
  back_app:
    depends_on:
      - db
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    environment:
      DB_URL: MONGO_DB
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'

volumes:
  mongodata:
